---
- name: Ensure group nginx-exp exists
  group:
    name: nginx-exp
    state: present
  become: true
- name: Add user 'nginx-exp' to a group
  user:
    name: nginx-exp
    groups: wheel, nginx-exp
  become: true
- name: Download nginx exporter 
  get_url:
    url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.3.0/nginx-prometheus-exporter-0.3.0-linux-amd64.tar.gz
    dest: ~
    mode: 0555
  become: true
- name: 