---
- name: Ensure group nginx-exp exists
  group:
    name: nginx-exp
    state: present
  become: true
- name: Add user 'nginx-exp' to a group
  user:
    name: nginx-exp
    groups: wheel, nginx-exp
  become: true
- name: Download and extract the nginx exporter
  get_url:
    url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.3.0/nginx-prometheus-exporter-0.3.0-linux-amd64.tar.gz
    dest: ~
    mode: 0555
  unarchive:
    src: ~
    dest: /usr/local/bin
    remote_src: true
  become: true
- name: Copies the nginx_exporter.service template
  template:
    src: files/nginx_exporter.service.j2
    dest: /etc/systemd/system/nginx_exporter.service
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: 0644
  become: true
- name: Make sure nginx_exporter service is running
  systemd:
    state: started
    name: nginx_exporter
  become: true
